services:
  app_container:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      mysql_db_container:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /app
