services:
  mysql_db_container:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
    healthcheck:
      test: [CMD, mysqladmin, ping, -h, localhost]
      timeout: 20s
      retries: 10
      start_period: 30s

volumes:
  mysql_db_data_container:
