services:
  mysql_db_container:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
    healthcheck:
      test: [CMD, mysqladmin, ping, -h, localhost]
      timeout: 20s
      retries: 10
      start_period: 30s

  app_container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      mysql_db_container:
        condition: service_healthy

volumes:
  mysql_db_data_container:
