FROM node:22.18.0-alpine3.21
WORKDIR /app

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY ./server/database/schema.prisma ./server/database/schema.prisma
RUN pnpm prisma generate

COPY . .

EXPOSE 3000
CMD ["pnpm", "run", "dev"]
